name: 'convert-issue-extension'
description: 'extend convert-issue for adding information.'
inputs:
  githubToken:
    description: 'github personal access token. repo and project permission'
    required: true
  issueId:
    description: 'issue id or pr id'
    required: true
  projectNumber:
    description: 'target project number.'
    required: true
  issueTitle:
    description: 'issue title which is parsed for updating'
    required: true
  shouldSyncWithTrackedInIssue:
    description: 'if you need to sync the issue with tracked-in-issue, you need to change true'
    required: false
    default: "false"
  shouldAddProjectIfNeeded:
    description: 'if you need to add the issue to the project, you need to change true'
    required: false
    default: "true"
outputs:
  itemId:
    description: 'card node id'
runs:
  using: 'node16'
  main: 'dist/index.js'
